apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-demo
  namespace: devsecops-demo
  labels:
    app: devsecops-demo
  annotations:
    checkov.io/skip1: CKV_K8S_8
    checkov.io/skip2: CKV_K8S_9
    checkov.io/skip3: CKV_K8S_14
    checkov.io/skip4: CKV_K8S_43
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devsecops-demo
  template:
    metadata:
      labels:
        app: devsecops-demo
      # annotations:
      #   vault.hashicorp.com/agent-inject: 'true'
      #   vault.hashicorp.com/role: 'dso-demo'
      #   vault.hashicorp.com/agent-inject-secret-database: 'secret/dso-demo/database'
      #   vault.hashicorp.com/agent-inject-status: 'update'
      #   vault.hashicorp.com/agent-inject-template-database: |
      #     {{- with secret "secret/dso-demo/database" -}}
      #       mysql -u {{ .Data.data.username }} -p {{ .Data.data.password }} -h database:3306 mydb
      #     {{- end -}}
    spec:
      serviceAccountName: devsecops-demo
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
        runAsUser: 11000
      containers:
      - name: devsecops-demo
        image: manuelnucci/lfs262-devsecops-demo
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        securityContext:
          capabilities:
            drop:
              - "ALL"
          privileged: false
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        resources:
          requests:
            cpu: "250m"
            memory: "64Mi"
          limits:
            cpu: "500m"
            memory: "128Mi"
        volumeMounts:
          - name: tmp
            mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
