apiVersion: v1
kind: Service
metadata:
  name: devsecops-demo
  labels:
    app: devsecops-demo
spec:
  type: NodePort
  selector:
    app: devsecops-demo
  ports:
  - name: http
    port: 8080
    nodePort: 30080
    protocol: TCP
    targetPort: 8080
